/** All system permissions. Use via <Can> or usePermissions() — never check role directly. */
export enum Permission {
  // Rides (admin)
  RIDE_ADMIN_VIEW = "RIDE_ADMIN_VIEW",
  RIDE_ADMIN_UPDATE = "RIDE_ADMIN_UPDATE",
  RIDE_ADMIN_CANCEL = "RIDE_ADMIN_CANCEL",

  // Passengers (admin)
  PASSENGER_ADMIN_VIEW = "PASSENGER_ADMIN_VIEW",
  PASSENGER_ADMIN_DELETE = "PASSENGER_ADMIN_DELETE",
  PASSENGER_ADMIN_REACTIVATE = "PASSENGER_ADMIN_REACTIVATE",

  // Vehicles (admin)
  VEHICLE_ADMIN_VIEW = "VEHICLE_ADMIN_VIEW",
  VEHICLE_ADMIN_UPDATE = "VEHICLE_ADMIN_UPDATE",
  VEHICLE_ADMIN_DELETE = "VEHICLE_ADMIN_DELETE",

  // Vehicle Reference
  VEHICLE_REFERENCE_VIEW = "VEHICLE_REFERENCE_VIEW",
  VEHICLE_REFERENCE_CREATE = "VEHICLE_REFERENCE_CREATE",
  VEHICLE_REFERENCE_UPDATE = "VEHICLE_REFERENCE_UPDATE",
  VEHICLE_REFERENCE_DELETE = "VEHICLE_REFERENCE_DELETE",

  // Service Categories
  SERVICE_CATEGORY_VIEW = "SERVICE_CATEGORY_VIEW",
  SERVICE_CATEGORY_CREATE = "SERVICE_CATEGORY_CREATE",
  SERVICE_CATEGORY_UPDATE = "SERVICE_CATEGORY_UPDATE",
}
